(* λ-1 translator — Standard ML prelude (MLton) *)

datatype D = Fun of D -> D | Num of int | Str of string

fun app (Fun f) x = f x
  | app _ _ = raise Fail "applied a non-function"

fun encodeInt n =                 (* host int -> チャーチ数 *)
  Fun (fn f => Fun (fn x =>
    let
      fun go 0 acc = acc
        | go k acc = go (k - 1) (app f acc)
    in go n x end))

fun decodeInt t =                 (* Num を注入して数える *)
  let
    val incr = Fun (fn v => case v of Num k => Num (k + 1) | _ => raise Fail "incr")
  in
    case app (app t incr) (Num 0) of Num k => Int.toString k | _ => raise Fail "decodeInt"
  end

fun decodeBool t =                (* Str を注入 *)
  case app (app t (Str "true")) (Str "false") of Str s => s | _ => raise Fail "decodeBool"

val failures = ref 0

fun check label a b =
  if a = b then print ("ok   " ^ label ^ "\n")
  else (failures := !failures + 1;
        print ("FAIL " ^ label ^ ": " ^ a ^ " != " ^ b ^ "\n"))

fun finish () =
  if !failures > 0 then
    (print (Int.toString (!failures) ^ " failure(s)\n"); OS.Process.exit OS.Process.failure)
  else print "all green\n"

(* ============ JSON 層（型付き値。ADR-0005） ============ *)
val jKsel  = Fun (fn a => Fun (fn _ => a))
val jKIsel = Fun (fn _ => Fun (fn b => b))
fun mkpair a b = Fun (fn s => app (app s a) b)
fun fstp p = app p jKsel
fun sndp p = app p jKIsel

val churchIncr = Fun (fn v => case v of Num k => Num (k + 1) | _ => raise Fail "churchIncr")
fun churchToInt c = case app (app c churchIncr) (Num 0) of Num k => k | _ => raise Fail "churchToInt"

val cTrue  = Fun (fn t => Fun (fn _ => t))
val cFalse = Fun (fn _ => Fun (fn f => f))
fun boolToHost c = case app (app c (Str "T")) (Str "F") of Str "T" => true | _ => false

val nilH = Fun (fn n => Fun (fn _ => n))
fun consH h t = Fun (fn _ => Fun (fn c => app (app c h) t))
fun isNil lst = boolToHost (app (app lst cTrue) (Fun (fn _ => Fun (fn _ => cFalse))))
fun headL lst = app (app lst (Str "")) (Fun (fn h => Fun (fn _ => h)))
fun tailL lst = app (app lst (Str "")) (Fun (fn _ => Fun (fn t => t)))
fun walkL lst = if isNil lst then [] else headL lst :: walkL (tailL lst)

fun jInt n = mkpair (encodeInt 1) (encodeInt n)
fun jBool b = mkpair (encodeInt 2) b
fun jStr s =
  mkpair (encodeInt 3)
    (List.foldr (fn (ch, lst) => consH (encodeInt (Char.ord ch)) lst) nilH (String.explode s))
fun jArr lst = mkpair (encodeInt 4) lst
fun jObj lst = mkpair (encodeInt 5) lst
val jNull = mkpair (encodeInt 6) (Fun (fn x => x))

fun jsonEscape s =
  let
    fun esc c =
      if c = #"\"" then "\\\""
      else if c = #"\\" then "\\\\"
      else String.str c
  in
    "\"" ^ String.concat (map esc (String.explode s)) ^ "\""
  end

fun decodeJson v =
  let
    val tag = churchToInt (fstp v)
    val payload = sndp v
  in
    case tag of
        1 => Int.toString (churchToInt payload)
      | 2 => if boolToHost payload then "true" else "false"
      | 3 => jsonEscape (String.implode (map (fn c => Char.chr (churchToInt c)) (walkL payload)))
      | 4 => "[" ^ String.concatWith "," (map decodeJson (walkL payload)) ^ "]"
      | 5 => "{" ^ String.concatWith ","
               (map (fn pr => decodeJson (fstp pr) ^ ":" ^ decodeJson (sndp pr)) (walkL payload)) ^ "}"
      | 6 => "null"
      | _ => "?"
  end

(* --- definitions --- *)
val v_mult = (Fun (fn v_m => (Fun (fn v_n => (Fun (fn v_f => (app v_m (app v_n v_f))))))))

(* --- assertions --- *)
val _ = check "assert 1" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 2" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 3" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 4" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 5" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 6" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 7" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 8" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 9" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 10" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 11" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 12" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 13" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 14" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 15" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 16" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 17" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 18" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 19" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 20" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 21" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 22" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 23" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 24" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 25" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 26" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 27" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 28" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 29" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 30" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 31" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 32" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 33" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 34" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 35" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 36" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 37" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 38" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 39" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 40" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 41" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 42" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 43" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 44" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 45" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 46" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 47" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 48" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 49" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 50" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 51" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 52" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 53" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 54" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 55" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 56" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 57" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 58" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 59" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 60" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 61" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 62" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 63" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 64" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 65" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 66" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 67" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 68" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 69" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 70" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 71" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 72" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 73" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 74" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 75" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 76" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 77" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 78" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 79" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 80" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 81" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 82" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 83" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 84" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 85" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 86" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 87" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 88" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 89" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 90" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 91" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 92" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 93" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 94" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 95" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 96" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 97" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 98" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 99" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 100" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 101" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 102" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 103" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 104" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 105" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 106" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 107" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 108" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 109" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 110" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 111" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 112" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 113" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 114" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 115" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 116" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 117" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 118" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 119" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 120" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 121" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 122" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 123" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 124" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 125" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 126" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 127" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 128" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 129" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 130" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 131" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 132" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 133" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 134" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 135" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 136" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 137" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 138" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 139" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 140" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 141" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 142" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 143" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 144" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 145" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 146" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 147" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 148" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 149" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 150" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 151" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 152" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 153" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 154" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 155" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 156" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 157" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 158" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 159" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 160" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 161" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 162" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 163" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 164" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 165" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 166" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 167" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 168" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 169" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 170" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 171" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 172" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 173" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 174" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 175" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 176" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 177" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 178" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 179" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 180" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 181" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 182" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 183" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 184" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 185" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 186" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 187" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 188" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 189" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 190" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 191" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 192" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 193" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 194" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 195" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 196" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 197" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 198" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 199" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 200" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 201" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 202" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 203" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 204" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 205" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 206" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 207" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 208" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 209" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 210" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 211" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 212" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 213" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 214" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 215" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 216" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 217" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 218" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 219" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 220" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 221" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 222" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 223" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 224" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 225" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 226" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 227" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 228" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 229" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 230" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 231" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 232" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 233" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 234" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 235" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 236" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 237" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 238" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 239" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 240" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 241" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 242" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 243" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 244" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 245" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 246" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 247" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 248" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 249" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 250" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 251" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 252" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 253" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 254" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 255" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 256" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 257" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 258" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 259" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 260" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 261" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 262" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 263" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 264" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 265" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 266" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 267" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 268" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 269" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 270" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 271" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 272" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 273" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 274" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 275" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 276" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 277" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 278" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 279" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 280" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 281" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 282" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 283" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 284" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 285" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 286" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 287" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 288" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 289" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 290" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 291" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 292" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 293" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 294" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 295" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 296" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 297" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 298" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 299" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 300" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 301" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 302" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 303" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 304" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 305" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 306" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 307" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 308" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 309" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 310" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 311" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 312" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 313" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 314" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 315" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 316" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 317" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 318" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 319" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 320" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 321" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 322" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 323" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 324" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 325" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 326" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 327" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 328" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 329" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 330" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 331" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 332" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 333" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 334" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 335" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 336" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 337" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 338" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 339" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 340" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 341" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 342" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 343" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 344" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 345" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 346" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 347" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 348" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 349" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 350" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 351" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 352" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 353" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 354" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 355" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 356" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 357" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 358" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 359" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 360" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 361" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 362" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 363" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 364" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 365" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 366" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 367" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 368" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 369" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 370" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 371" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 372" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 373" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 374" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 375" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 376" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 377" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 378" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 379" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 380" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 381" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 382" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 383" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 384" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 385" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 386" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 387" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 388" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 389" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 390" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 391" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 392" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 393" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 394" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 395" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 396" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 397" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 398" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 399" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 400" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 401" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 402" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 403" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 404" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 405" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 406" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 407" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 408" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 409" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 410" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 411" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 412" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 413" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 414" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 415" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 416" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 417" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 418" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 419" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 420" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 421" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 422" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 423" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 424" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 425" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 426" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 427" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 428" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 429" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 430" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 431" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 432" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 433" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 434" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 435" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 436" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 437" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 438" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 439" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 440" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 441" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 442" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 443" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 444" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 445" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 446" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 447" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 448" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 449" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 450" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 451" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 452" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 453" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 454" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 455" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 456" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 457" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 458" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 459" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 460" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 461" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 462" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 463" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 464" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 465" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 466" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 467" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 468" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 469" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 470" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 471" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 472" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 473" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 474" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 475" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 476" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 477" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 478" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 479" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 480" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 481" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 482" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 483" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 484" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 485" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 486" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 487" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 488" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 489" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 490" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 491" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 492" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 493" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 494" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 495" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 496" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 497" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 498" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 499" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))
val _ = check "assert 500" ("900") ((decodeInt (app (app v_mult (encodeInt 30)) (encodeInt 30))))

val _ = finish ()
